# Nombre del pipeline que aparecerá en la pestaña "Actions" de GitHub
name: CI/CD Pipeline para API de Volatilidad

# Disparadores: Cuándo se debe ejecutar este pipeline
on:
  # Ejecutar en cada push a la rama principal (main o master)
  push:
    branches: [ "main", "master" ]
  # Ejecutar también en Pull Requests a la rama principal
  pull_request:
    branches: [ "main", "master" ]

# Trabajos: Las tareas que se ejecutarán
jobs:
  #--------- TRABAJO 1: PRUEBAS (CI) ---------
  test-app:
    # El tipo de máquina virtual donde se ejecutará
    runs-on: ubuntu-latest

    steps:
      # 1. Descarga tu código del repositorio a la máquina virtual
      - name: Checkout del código
        uses: actions/checkout@v4

      # 2. Configura el entorno de Python
      - name: Configurar Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # 3. Instala las dependencias del proyecto
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Ejecuta las pruebas con pytest
      - name: Ejecutar pruebas
        run: pytest

  #--------- TRABAJO 2: CONSTRUIR Y SUBIR IMAGEN (CD) ---------
  build-and-push-docker:
    # Este trabajo solo se ejecutará si el trabajo 'test-app' ha terminado con éxito
    needs: test-app
    runs-on: ubuntu-latest

    steps:
      # 1. Descarga tu código del repositorio
      - name: Checkout del código
        uses: actions/checkout@v4

      # 2. Inicia sesión en Docker Hub
      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Construye la imagen de Docker y la sube a Docker Hub
      - name: Construir y subir imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Etiqueta la imagen con tu nombre de usuario de Docker Hub y el nombre del repo
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/btc-volatility-api:latest